### PR TITLE
finishing capstone project

### PR DESCRIPTION
**Pull request by fickryiman**
- adjustment for footer

The below details have merged to the master branch:
- mobile version has been done/merged
- desktop version has been done/merged
- dynamic page has been done/merged
- the mobile menu has been done/merged

### CODE REVIEW

**Review by shella12 — CHANGES_REQUESTED** [review]
Hi @fickryiman , 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!



## Suggested changes

- [x] You have done a great job your website looks amazing 👍 however please make sure to make a video of maximum five minutes on the loom talking about the features of your website and some interesting piece of code that you are really proud of.
- [x] Please make sure to give appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/) in the README "Acknowledgements" section or similar.

Screenshot 2023-03-17 at 7 32 42 AM

## Optional suggestions 

_You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can consider:
- [OPTIONAL] Great job adding `more` button to your project as an additional requirement, I suggest also adding a show less button along with it so when the more button is clicked it's text should be changed to `less` and when we click the less button it should show less speakers
- [OPTIONAL] Please make sure to always code in the feature branch instead of master branch. The core idea behind the Feature Branch Workflow is that all feature development should take place in a dedicated branch instead of the main branch. This encapsulation makes it easy for multiple developers to work on a particular feature without disturbing the main codebase.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by fickryiman** [comment]
Add acknowledgement, credit to the author of this design:

image

**Comment by fickryiman** [comment]
_[OPTIONAL] Great job adding more button to your project as an additional requirement, I suggest also adding a show less button along with it so when the more button is clicked it's text should be changed to less and when we click the less button it should show less speakers_

**this optional has Created and DONE!**

**Comment by fickryiman** [comment]
Create a video description of this project, the interesting parts of the code, and features in this project

**Review by IngDavidTM — APPROVED** [review]
Hi @fickryiman 🙋‍♂️, 

# ✔️   Status: APPROVED 🏆 🎉 🎊 

You have done a great job on this project, keep it up 👍 🥇. Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations!  🎉💯🌟 

## Top highlight 🎯

- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by fickryiman** [comment]
Cool, Thank you reviewers

**Pull request merged**
